//CONTACT ACTIONS
export const ADD_CONTACT = 'ADD_CONTACT'

//LOGIN ACTIONS
export const CREATE_ID ='CREATE_ID'

//TOTAL ACTIONS
export const SET_TOTAL = 'SET_TOTAL'
export const SET_NUMBER_GOAL = 'SET_NUMBER_GOAL'

//LOG ACTIONS

export const ADD_MESSAGE = 'ADD_MESSAGE';